name: brazukas-app-discord
region: atl
services:
  - name: nist-discord-bot
    # Força uso do Dockerfile
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: PedroNhoura/nist-discord-bot
      branch: main
      deploy_on_push: true
    # Environment variables
    envs:
      - key: DISCORD_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: DISCORD_CHANNEL_ID
        scope: RUN_TIME
        value: "1451316595661209642"
      - key: NVD_API_KEY
        scope: RUN_TIME
        type: SECRET
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    # HTTP settings
    http_port: 8080
    routes:
      - path: /
    # Instance size
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb-fixed
